# Generated by Django 4.2 on 2024-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('about_me', models.TextField()),
                ('experience', models.TextField()),
                ('role', models.CharField(choices=[('Mentor', 'Mentor'), ('Learner', 'Learner')], max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('mentor_contact', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=50)),
                ('learner_contact', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='profile_images/')),
            ],
        ),
    ]
