# Generated by Django 4.2 on 2024-12-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0002_rename_fullname_profile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about_me',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='learner_contact',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='mentor_contact',
            new_name='reach',
        ),
    ]
