# Generated by Django 4.2 on 2024-12-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0004_rename_fullname_profile_name_alter_profile_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reach',
            new_name='phone',
        ),
    ]
